#!/bin/sh
set -e
export RUNNING_ENV="$1"
. ./scripts/env_vars.sh
./scripts/setup_initial.sh

sudo docker network create npm_net || true

case "$RUNNING_ENV" in
    dev)
        dev_command="$2"
        ./scripts/dev.sh "$dev_command"
        ;;
    prod)
        sudo -E docker compose -f "$DOCKER_COMPOSE_FILE" up --wait
        # sudo -E docker compose -f "$DOCKER_COMPOSE_FILE" up brag-server --build
        ;;
    clean_prod)
        sudo rm -rf  "$PROD_WD"/"$DATA_PATH"
        sudo systemctl disable spin_db.service --now
        sudo systemctl disable load_db.service --now
        sudo systemctl disable brag-server.service --now
        ;;
    *)
        echo 'run main: Error: Invalid input. Please enter "dev" or "prod"'
        exit 1
        ;;
esac
