#!/bin/sh
. ./.env

case $1 in
    dev)
        ./scripts/dev.sh "$2"
        ;;
    prod)
        ./scripts/prod.sh
        ;;
    *)
        echo 'Error: Invalid input. Please enter "dev" or "build"'
        exit 1
        ;;
esac
