#!/bin/sh
set -e
export RUNNING_ENV="$1"
. ./scripts/env_vars.sh
./scripts/setup_initial.sh

sudo docker network create npm_net || true

case "$RUNNING_ENV" in
    dev)
        dev_command="$2"
        ./scripts/dev.sh "$dev_command"
        ;;
    curl)
        sudo docker build -t curl-test -f Dockerfile-curl .
        sudo docker run --rm --network=npm_net curl-test
        ;;
    prod)
        sudo -E docker compose -f "$DOCKER_COMPOSE_FILE" up --wait --build
        ;;
    *)
        echo 'run main: Error: Invalid input. Please enter "dev" or "prod"'
        exit 1
        ;;
esac
