#!/bin/sh
. ./envs/db.env
docker compose down
sudo docker kill "$(sudo docker ps -q)"
sudo docker system prune -a -f && sudo docker volume prune -f
sudo docker network prune -f
sudo rm -rf "$DATA_PATH"
